import React, { useState } from "react";
import {
  DocumentArrowDownIcon,
  TableCellsIcon,
  CodeBracketIcon,
  DocumentTextIcon,
  CheckCircleIcon,
  ArrowDownTrayIcon,
  ExclamationTriangleIcon,
  ClockIcon,
  SparklesIcon,
} from "@heroicons/react/24/outline";
import { getTransactions } from "../services/api";

function ExportData() {
  const [exporting, setExporting] = useState(false);
  const [exported, setExported] = useState(null);
  const [selectedFormat, setSelectedFormat] = useState(null);
  const [transactionCount, setTransactionCount] = useState(null);
  const [showPreview, setShowPreview] = useState(false);

  const fetchAllTransactions = async () => {
    const allTransactions = [];
    let page = 1;
    let hasMore = true;

    while (hasMore) {
      const response = await getTransactions({ page, limit: 100, sort: '-date' });
      const data = response.data?.data || response.data || [];
      allTransactions.push(...data);
      const totalPages = response.data?.pages || 1;
      hasMore = page < totalPages;
      page++;
    }

    return allTransactions;
  };

  const formatTransactions = (transactions) => {
    return transactions.map(t => ({
      date: new Date(t.date).toISOString().split('T')[0],
      type: t.type,
      category: t.category,
      description: t.description || '',
      amount: t.amount,
      paymentMethod: t.paymentMethod || 'cash',
      location: t.location || '',
      notes: t.notes || ''
    }));
  };

  const exportAsCSV = (transactions) => {
    const formatted = formatTransactions(transactions);
    const headers = ['Date', 'Type', 'Category', 'Description', 'Amount', 'Payment Method', 'Location', 'Notes'];
    let csv = headers.join(',') + '\n';
    formatted.forEach(row => {
      csv += [
        row.date, `"${row.type}"`, `"${row.category}"`,
        `"${row.description.replace(/"/g, '""')}"`, row.amount,
        `"${row.paymentMethod}"`, `"${row.location}"`,
        `"${row.notes.replace(/"/g, '""')}"`
      ].join(',') + '\n';
    });
    return csv;
  };

  const exportAsJSON = (transactions) => {
    const formatted = formatTransactions(transactions);
    const summary = {
      export_date: new Date().toISOString(),
      total_transactions: transactions.length,
      total_income: transactions.filter(t => t.type === 'income').reduce((sum, t) => sum + t.amount, 0),
      total_expenses: transactions.filter(t => t.type === 'expense').reduce((sum, t) => sum + t.amount, 0),
      balance: transactions.filter(t => t.type === 'income').reduce((sum, t) => sum + t.amount, 0) - transactions.filter(t => t.type === 'expense').reduce((sum, t) => sum + t.amount, 0),
      transactions: formatted
    };
    return JSON.stringify(summary, null, 2);
  };

  const exportAsHTML = (transactions) => {
    const formatted = formatTransactions(transactions);
    const totalIncome = transactions.filter(t => t.type === 'income').reduce((sum, t) => sum + t.amount, 0);
    const totalExpenses = transactions.filter(t => t.type === 'expense').reduce((sum, t) => sum + t.amount, 0);
    return `<!DOCTYPE html><html><head><title>Expense Report</title><style>body{font-family:Arial,sans-serif;padding:20px;max-width:1000px;margin:auto}h1{color:#1a1a2e}table{width:100%;border-collapse:collapse;margin-top:20px}th{background:#1a1a2e;color:#fff;padding:12px;text-align:left}td{padding:10px;border-bottom:1px solid #e0e0e0}tr:hover{background:#f5f5f5}.income{color:#10B981;font-weight:600}.expense{color:#EF4444;font-weight:600}.summary{display:flex;gap:20px;margin:20px 0}.summary-box{flex:1;padding:20px;border-radius:12px;text-align:center}.summary-box.income{background:#ECFDF5}.summary-box.expense{background:#FEF2F2}.summary-box.balance{background:#EFF6FF}</style></head><body><h1>💰 Expense Tracker Report</h1><p>Generated: ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p><div class="summary"><div class="summary-box income"><p>Total Income</p><h2>$${totalIncome.toFixed(2)}</h2></div><div class="summary-box expense"><p>Total Expenses</p><h2>$${totalExpenses.toFixed(2)}</h2></div><div class="summary-box balance"><p>Balance</p><h2>$${(totalIncome - totalExpenses).toFixed(2)}</h2></div></div><table><thead><tr><th>Date</th><th>Type</th><th>Category</th><th>Description</th><th>Amount</th><th>Payment</th></tr></thead><tbody>${formatted.map(t => `<tr><td>${t.date}</td><td class="${t.type}">${t.type}</td><td>${t.category}</td><td>${t.description}</td><td class="${t.type}">$${t.amount.toFixed(2)}</td><td>${t.paymentMethod}</td></tr>`).join('')}</tbody></table><p style="text-align:center;margin-top:30px;color:#999">Generated by AI Expense Tracker</p></body></html>`;
  };

  const downloadFile = (content, filename, type) => {
    const blob = new Blob([content], { type });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    link.remove();
    window.URL.revokeObjectURL(url);
  };

  const handleExport = async (format) => {
    setExporting(true);
    setSelectedFormat(format);
    setExported(null);

    try {
      const transactions = await fetchAllTransactions();
      setTransactionCount(transactions.length);

      if (transactions.length === 0) {
        alert("No transactions to export. Add some transactions first.");
        return;
      }

      const date = new Date().toISOString().split('T')[0];
      switch (format) {
        case 'csv':
          downloadFile(exportAsCSV(transactions), `expenses_${date}.csv`, 'text/csv');
          break;
        case 'json':
          downloadFile(exportAsJSON(transactions), `expenses_${date}.json`, 'application/json');
          break;
        case 'html':
          downloadFile(exportAsHTML(transactions), `expense_report_${date}.html`, 'text/html');
          break;
      }
      setExported(format);
      setTimeout(() => setExported(null), 3000);
    } catch (error) {
      
      alert(`Failed to export as ${format.toUpperCase()}. Please try again.`);
    } finally {
      setExporting(false);
      setSelectedFormat(null);
    }
  };

  const getColorClasses = (color) => {
    const colors = {
      emerald: { bg: 'bg-emerald-500/10', border: 'border-emerald-500/20', text: 'text-emerald-400', btn: 'from-emerald-500 to-teal-500', icon: '👔' },
      blue: { bg: 'bg-blue-500/10', border: 'border-blue-500/20', text: 'text-blue-400', btn: 'from-blue-500 to-indigo-500', icon: '📄' },
      purple: { bg: 'bg-purple-500/10', border: 'border-purple-500/20', text: 'text-purple-400', btn: 'from-purple-500 to-pink-500', icon: '💻' },
      yellow: { bg: 'bg-yellow-500/10', border: 'border-yellow-500/20', text: 'text-yellow-400', btn: 'from-yellow-500 to-orange-500', icon: '📊' },
    };
    return colors[color] || colors.emerald;
  };

  const exportOptions = [
    { format: "csv", label: "CSV Spreadsheet", icon: TableCellsIcon, description: "Best for Excel, Google Sheets, and data analysis", color: "emerald", features: ["Opens in any spreadsheet", "Comma-separated values", "Includes all fields"] },
    { format: "html", label: "HTML Report", icon: DocumentTextIcon, description: "Beautiful printable report with summary", color: "blue", features: ["Professional layout", "Print-ready format", "Summary dashboard"] },
    { format: "json", label: "JSON Backup", icon: CodeBracketIcon, description: "Complete data export for backups and developers", color: "purple", features: ["Full data structure", "Machine-readable", "Includes metadata"] },
  ];

  return (
    <div className="max-w-5xl mx-auto">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-2">
          <div className="w-10 h-10 bg-gradient-to-br from-yellow-400 to-orange-500 rounded-xl flex items-center justify-center shadow-lg shadow-yellow-500/20">
            <ArrowDownTrayIcon className="h-6 w-6 text-white" />
          </div>
          <h1 className="text-3xl font-bold text-white">Export Data</h1>
        </div>
        <p className="text-gray-400 ml-13">Download your financial data in multiple formats</p>
      </div>

      {/* Quick Stats */}
      <div className="grid grid-cols-3 gap-4 mb-8">
        {[
          { label: 'Formats', value: '3', icon: DocumentArrowDownIcon, color: 'yellow' },
          { label: 'Data Points', value: '8 fields', icon: TableCellsIcon, color: 'emerald' },
          { label: 'All Time', value: 'Complete', icon: ClockIcon, color: 'blue' },
        ].map((stat, i) => (
          <div key={i} className="bg-gray-800/30 backdrop-blur-xl rounded-xl border border-gray-700/50 p-4 text-center">
            <stat.icon className="h-5 w-5 text-gray-500 mx-auto mb-2" />
            <p className="text-white font-bold text-lg">{stat.value}</p>
            <p className="text-gray-500 text-xs">{stat.label}</p>
          </div>
        ))}
      </div>

      {/* Export Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        {exportOptions.map((option) => {
          const colors = getColorClasses(option.color);
          return (
            <div key={option.format} className={`${colors.bg} backdrop-blur-xl rounded-2xl border ${colors.border} p-6 hover:shadow-lg transition-all duration-300 group`}>
              {/* Icon */}
              <div className={`w-14 h-14 rounded-2xl ${colors.bg} border ${colors.border} flex items-center justify-center mb-5 group-hover:scale-110 transition-transform`}>
                <option.icon className={`h-7 w-7 ${colors.text}`} />
              </div>

              {/* Content */}
              <h3 className="text-white font-semibold text-lg mb-2">{option.label}</h3>
              <p className="text-gray-400 text-sm mb-4 leading-relaxed">{option.description}</p>

              {/* Features */}
              <ul className="space-y-2 mb-6">
                {option.features.map((f, i) => (
                  <li key={i} className="flex items-center gap-2 text-xs text-gray-400">
                    <CheckCircleIcon className="h-3.5 w-3.5 text-emerald-400 flex-shrink-0" />
                    {f}
                  </li>
                ))}
              </ul>

              {/* Button */}
              <button
                onClick={() => handleExport(option.format)}
                disabled={exporting}
                className={`w-full py-3 px-4 rounded-xl font-semibold text-sm transition-all duration-300 flex items-center justify-center gap-2 ${
                  exported === option.format
                    ? 'bg-emerald-500 text-white'
                    : `bg-gradient-to-r ${colors.btn} text-white hover:shadow-lg hover:scale-[1.02]`
                } disabled:opacity-50 disabled:cursor-not-allowed`}
              >
                {exporting && selectedFormat === option.format ? (
                  <>
                    <div className="animate-spin rounded-full h-4 w-4 border-2 border-white border-t-transparent"></div>
                    <span>Exporting...</span>
                  </>
                ) : exported === option.format ? (
                  <>
                    <CheckCircleIcon className="h-5 w-5" />
                    <span>Downloaded!</span>
                  </>
                ) : (
                  <>
                    <ArrowDownTrayIcon className="h-5 w-5" />
                    <span>Export {option.label.split(' ')[0]}</span>
                  </>
                )}
              </button>
            </div>
          );
        })}
      </div>

      {/* Transaction Count */}
      {transactionCount !== null && (
        <div className="mb-8 p-4 bg-gray-800/30 backdrop-blur-xl rounded-xl border border-gray-700/50 text-center">
          <p className="text-gray-400 text-sm">
            <span className="text-white font-semibold">{transactionCount}</span> transactions available for export
          </p>
        </div>
      )}

      {/* Info Section */}
      <div className="bg-gray-800/30 backdrop-blur-xl rounded-2xl border border-gray-700/50 p-8">
        <div className="flex items-center gap-3 mb-6">
          <div className="p-2 bg-yellow-500/10 rounded-xl border border-yellow-500/20">
            <SparklesIcon className="h-5 w-5 text-yellow-400" />
          </div>
          <h3 className="text-white font-semibold text-lg">What's Included</h3>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {[
            { title: 'Transaction Details', items: ['Date & time', 'Amount', 'Category', 'Description'] },
            { title: 'Payment Info', items: ['Payment method', 'Location', 'Notes', 'Tags'] },
            { title: 'Summary Stats', items: ['Total income', 'Total expenses', 'Net balance', 'Export date'] },
          ].map((section, i) => (
            <div key={i}>
              <h4 className="text-white text-sm font-medium mb-3">{section.title}</h4>
              <ul className="space-y-2">
                {section.items.map((item, j) => (
                  <li key={j} className="flex items-center gap-2 text-sm text-gray-400">
                    <div className="w-1.5 h-1.5 bg-yellow-500/50 rounded-full flex-shrink-0"></div>
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        {/* Tip */}
        <div className="mt-6 p-4 bg-yellow-500/5 rounded-xl border border-yellow-500/10 flex items-start gap-3">
          <span className="text-lg">💡</span>
          <p className="text-gray-400 text-sm">
            <span className="text-white font-medium">Pro Tip:</span> CSV files work great with Excel and Google Sheets. 
            JSON format is perfect for creating backups that can be re-imported. 
            HTML reports are ideal for printing or sharing via email.
          </p>
        </div>
      </div>
    </div>
  );
}

export default ExportData;